# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ignacio Carlucho
tagline:          'A Jekyll theme'
description:      'PhD student at the National University of Central Buenos Aires. Main interest are Reinforcement Learning for Underwater Robotics'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/IgnacioCarlucho
